### ISSUE TITLE
Angular updates todo list

### ISSUE THREAD

**Issue by colemanw** [civicrm/org.civicrm.volunteer#573]
- [ ] Use one-time-binding for static content or the output of deterministic functions, e.g. #570
- [ ] Move server-side module definition into an `.ang.php` file and out of `hook_civicrm_angularModules()` - revert that function to delegate to `_volunteer_civix_civicrm_angularModules()` .
- [ ] Break up monolithic "volunteer" Angular module into smaller bite-sized modules.
- [ ] Break up `CRM_Volunteer_Page_Angular` into front-end and back-end pages, and only load the modules needed for each.
- [ ] Use components instead of directives or controllers when possible.
- [ ] Break up monolithic js files into one file per component/directive.
- [ ] Pre-load backbone code on the back-end angular pages instead of depending on the clientside script loading done by `angularprofiles` (which is broken on some CMS configurations, see https://github.com/civicrm/org.civicrm.contactlayout/commit/24f9a1f1dacb0b8e2300069495eb71d211e4e481)
- [ ] Stop using AJAX to load Angular tab content - core now supports loading it directly

**Comment by ginkgomzd** [comment]
This looks great

**Comment by ginkgomzd** [comment]
blocked by
 * #569 
 * #570 
 * #571 
 * #572

**Comment by ginkgomzd** [comment]
Hey, @colemanw ,
Responding to your mattermost msg here because it is easier without a computer. 

I'm moving tomorrow and have been short on time this week due to packing. 

So, no questions on the PR's yet. If you are holding PR's, you could go ahead and make them and just note the dependency on the order they are merged.
